import type { PlanData } from "@/types/plan";

/** Single source of truth for tom skjema + fallback når utkast i localStorage er ugyldig. */
export const planDefaultValues: PlanData = {
  prosjektnavn: "",
  entreprenor: "",
  byggherre: "",
  ansvarligPerson: "",
  dokumentnummer: "",
  underprosjekt: "",
  fkpAnsvarligGroft: "",
  fkpAnsvarligGjennomforing: "",
  fkpSammePerson: false,
  personerIGroft: "",
  personerIGroftRader: [{ navn: "", rolle: "" }],
  dato: new Date().toISOString().slice(0, 10),
  revisjonsnummer: "R0",
  adresse: "",
  kommune: "",
  arbeidsomrade: "",
  groftelengdeMeter: 20,
  maksDybdeMeter: 1.2,
  breddeBunnMeter: 0.8,
  breddeToppMeter: 1.8,
  etappebeskrivelse: "",
  dybdeOver125: false,
  dybdeOver200: false,
  jordart: "sand",
  grunnvann: false,
  skraningINarheten: false,
  byggINarheten: false,
  trafikkbelastningNarGroft: false,
  ingenKjenteInstallasjoner: true,
  trafikkStegIkkeAktuelt: true,
  geotekniskBehov: false,
  grunnundersokelseProvegraving: false,
  grunnundersokelseGrunnboring: false,
  grunnundersokelseSondering: false,
  grunnundersokelseIkkeForetatt: true,
  grunnundersokelseAnnet: "",
  avstivingBehov: "",
  avstivingKommentar: "",
  lengdeprofilRader: [{ pel: "", masse: "", dybde: "" }],
  plan215Lengdeprofil: "",
  plan215Jordarter: "",
  plan215Tverrprofil: "",
  plan215Gravemasser: "",
  plan215Arbeidsinstruks: "",
  installasjonVa: false,
  installasjonOvervann: false,
  installasjonSpillvann: false,
  installasjonHoyspent: false,
  installasjonLavspent: false,
  installasjonFiberTele: false,
  installasjonGassFjernvarme: false,
  installasjonUkjent: false,
  kabelpavisningUtfort: false,
  sikringsmetode: "ikke relevant",
  sikringBeskrivelse: "",
  romningsvei: "",
  avsperring: "",
  plasseringGravemasser: "",
  avstandFraGroftekantMeter: 1,
  mellomlagring: "",
  massetransport: "",
  arbeidsbeskrivelse: "",
  sikkerJobbAnalyseUtfort: false,
  dagligKontroll: false,
  kontrollEtterUvaer: false,
  stoppkriterier: "",
  kontrollpunkter: "",
  utarbeidetAv: "",
  kontrollertAv: "",
  utarbeidetSignatur: "",
  kontrollertSignatur: "",
  godkjentSignatur: "",
  godkjentAv: "",
  godkjentDato: "",
  signaturDato: new Date().toISOString().slice(0, 10),
  skisseTverrprofilTittel: "Typisk tverrprofil",
  skisseLengdeprofilTittel: "Planvisning (fugleperspektiv)",
  skisseTerrengLabel: "Terrenglinje",
  skisseLedningLabel: "Rør/ledning i bunn",
  skisseMasserLabel: "Gravemasser",
  skisseVisSymboler: true,
  skisseMal: "template-01-skraasider",
  skisseLedningSymbol: "sirkel",
  skisseMasserSymbol: "firkant",
  skisseDybdeMeter: 1.2,
  skisseBreddeBunnMeter: 0.8,
  skisseBreddeToppMeter: 1.8,
  skisseMasseAvstandMeter: 1,
  skisseLengdeMeter: 20
};
