import { z } from "zod";
import { jordarter, sikringsmetoder, skisseMaler, skisseSymboler } from "@/types/plan";

export const planSchema = z.object({
  prosjektnavn: z.string().min(2, "Prosjektnavn er påkrevd."),
  entreprenor: z.string().min(2, "Entreprenør er påkrevd."),
  byggherre: z.string().min(2, "Byggherre er påkrevd."),
  ansvarligPerson: z.string().min(2, "Ansvarlig person er påkrevd."),
  dato: z.string().min(1, "Dato er påkrevd."),
  revisjonsnummer: z.string().min(1, "Revisjonsnummer er påkrevd."),
  adresse: z.string().min(2, "Adresse er påkrevd."),
  kommune: z.string().min(2, "Kommune er påkrevd."),
  arbeidsomrade: z.string().min(5, "Beskrivelse av arbeidsområdet er påkrevd."),
  groftelengdeMeter: z.number().min(1, "Oppgi grøftelengde."),
  maksDybdeMeter: z.number().min(0.1, "Oppgi maks dybde."),
  breddeBunnMeter: z.number().min(0.1, "Oppgi bredde i bunn."),
  breddeToppMeter: z.number().min(0.1, "Oppgi bredde i topp."),
  etappebeskrivelse: z.string().min(2, "Etappebeskrivelse er påkrevd."),
  dybdeOver125: z.boolean(),
  dybdeOver200: z.boolean(),
  jordart: z.enum(jordarter),
  grunnvann: z.boolean(),
  skraningINarheten: z.boolean(),
  byggINarheten: z.boolean(),
  trafikkbelastningNarGroft: z.boolean(),
  geotekniskBehov: z.boolean(),
  installasjonVa: z.boolean(),
  installasjonOvervann: z.boolean(),
  installasjonSpillvann: z.boolean(),
  installasjonHoyspent: z.boolean(),
  installasjonLavspent: z.boolean(),
  installasjonFiberTele: z.boolean(),
  installasjonGassFjernvarme: z.boolean(),
  installasjonUkjent: z.boolean(),
  kabelpavisningUtfort: z.boolean(),
  sikringsmetode: z.enum(sikringsmetoder),
  sikringBeskrivelse: z.string().min(2, "Beskrivelse av sikring er påkrevd."),
  romningsvei: z.string().optional().default(""),
  avsperring: z.string().min(2, "Avsperring/sikring er påkrevd."),
  plasseringGravemasser: z.string().min(2, "Beskriv plassering av gravemasser."),
  avstandFraGroftekantMeter: z.number().min(0, "Oppgi avstand fra grøftekant."),
  mellomlagring: z.string().min(2, "Beskriv mellomlagring."),
  massetransport: z.string().min(2, "Beskriv massetransport."),
  arbeidsbeskrivelse: z.string().min(5, "Arbeidsbeskrivelse er påkrevd."),
  sikkerJobbAnalyseUtfort: z.boolean(),
  dagligKontroll: z.boolean(),
  kontrollEtterUvaer: z.boolean(),
  stoppkriterier: z.string().min(2, "Stoppkriterier er påkrevd."),
  kontrollpunkter: z.string().min(2, "Kontrollpunkter er påkrevd."),
  utarbeidetAv: z.string().min(2, "Utarbeidet av er påkrevd."),
  kontrollertAv: z.string().min(2, "Kontrollert av er påkrevd."),
  signaturDato: z.string().min(1, "Signaturdato er påkrevd."),
  skisseTverrprofilTittel: z.string().min(2, "Oppgi tittel for tverrprofil."),
  skisseLengdeprofilTittel: z.string().min(2, "Oppgi tittel for lengdeprofil."),
  skisseTerrengLabel: z.string().min(2, "Oppgi etikett for terrenglinje."),
  skisseLedningLabel: z.string().min(2, "Oppgi etikett for ledning."),
  skisseMasserLabel: z.string().min(2, "Oppgi etikett for masser."),
  skisseVisSymboler: z.boolean(),
  skisseMal: z.enum(skisseMaler),
  skisseLedningSymbol: z.enum(skisseSymboler),
  skisseMasserSymbol: z.enum(skisseSymboler),
  skisseDybdeMeter: z.number().min(0.1, "Skissedybde må være minst 0,1 m."),
  skisseBreddeBunnMeter: z.number().min(0.1, "Skissebredde bunn må være minst 0,1 m."),
  skisseBreddeToppMeter: z.number().min(0.1, "Skissebredde topp må være minst 0,1 m."),
  skisseMasseAvstandMeter: z.number().min(0, "Skisseavstand for masser må være 0 eller mer."),
  skisseLengdeMeter: z.number().min(1, "Skisselengde må være minst 1 m.")
});

export type PlanSchema = z.infer<typeof planSchema>;
